### ISSUE TITLE
Post Install Tool Error

### ISSUE THREAD

**Issue by Drvt6713** [SKOPOS-ELEMENTS/SFTPTools_Alteryx#16]
After install was successful for Alteryx (Designer version 2023.2.1.7), in a very simple workflow to test the tool, I added the SFTP Downloader tool and immediately, before connecting any flow to it or entering any settings, I received the following error:

Error: SFTP Downloader (12): Traceback (most recent call last):
  File "main.py", line 5, in <module>
  File "C:\ProgramData\Alteryx\Tools\SKOPOS_SFTP_venv\Lib\site-packages\pysftp\__init__.py", line 12, in <module>
    import paramiko
  File "C:\ProgramData\Alteryx\Tools\SKOPOS_SFTP_venv\Lib\site-packages\paramiko\__init__.py", line 22, in <module>
    from paramiko.transport import (
  File "C:\ProgramData\Alteryx\Tools\SKOPOS_SFTP_venv\Lib\site-packages\paramiko\transport.py", line 33, in <module>
    from cryptography.hazmat.primitives.ciphers import algorithms, Cipher, modes
  File "C:\ProgramData\Alteryx\Tools\SKOPOS_SFTP_venv\Lib\site-packages\cryptography\hazmat\primitives\ciphers\__init__.py", line 11, in <module>
    from cryptography.hazmat.primitives.ciphers.base import (
  File "C:\ProgramData\Alteryx\Tools\SKOPOS_SFTP_venv\Lib\site-packages\cryptography\hazmat\primitives\ciphers\base.py", line 10, in <module>
    from cryptography.exceptions import (
  File "C:\ProgramData\Alteryx\Tools\SKOPOS_SFTP_venv\Lib\site-packages\cryptography\exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: DLL load failed while importing _rust: The specified module could not be found.

Wondering if any of it would resolve upon entering some settings, I did so as well as connected it to an incoming flow and nothing changed with the error.  Still there.

Let me know what I can do to correct the errors.
Thanks,

**Comment by PhillRogers** [comment]
I have this too, using v1.0.2 (the v1.0 failed to install) With Alteryx 2023.2.1.51  Patch: 1
I see no changes since May 2021 - has this been abandoned & superseded by something else?

**Comment by neurotroph** [comment]
@PhillRogers @Drvt6713 We are still using the plugin in many of our workflows, but remain on Alteryx 2022.3 right now.

The issue raised here is one with the underlying Python library, which also seems to be related to Alteryx' python version. It is also mentioned in some GitHub issues e.g. in the underlying library:
* https://github.com/pyca/cryptography/issues/9444
* https://github.com/pyinstaller/pyinstaller/issues/6390
* https://stackoverflow.com/questions/70201325/embedded-python-import-paramiko-fails-with-importerror-dll-load-failed-while

However, there doesn't seem to be an easy fix.

We would need to rewrite the whole plugin in order to use the latest Alteryx Platform SDK to be supported for future versions. As we are slowly migrating away from Alteryx, I cannot promise that we will actually do that, sorry.

**Comment by PhillRogers** [comment]
Hi,

Thanks for the info. Out of interest what are you slowly moving towards?
I've been happily using KNIME for a while and prefer it greatl, for what I do.

Regards,
Phill

Phill Rogers​​​​
CFTP
Automation Specialist
+
Switchboard:
+44 (0) 1534 761500
+
Direct:
+44 (0) 1534 761526<tel:+44%20(0)%201534%20761526>
+
Email:
***@***.******@***.***>
+
Website:
www.enhance.group<https://enhance.group/>
[facebook]<https://www.facebook.com/EnhanceGlobal/>
[LinkedIn]<https://www.linkedin.com/company/enhance-group/>
[Twitter]<https://twitter.com/enhanceje>
***@***.***

***@***.***

Registered Office: 3rd Floor, 29‑31 Esplanade, St Helier, Jersey, JE2 3QA
​
